config/routes.rb
Vanan::Application.routes.draw do
  resources :introduces

  resources :products

  resources :contacts

  get "home/index"

  root :to => 'home#index'

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  address     :string(255)
#  phone       :string(255)
#  email       :string(255)
#  title       :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Contact < ActiveRecord::Base
  attr_accessible :address, :description, :email, :name, :phone, :title

  # ============================= VALIDATIONS ===============================
  validates :address , :description , :presence => true

end

app/models/introduce.rb
class Introduce < ActiveRecord::Base
  attr_accessible :author, :content, :image, :summary, :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image, :name, :price, :status, :summary, :type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    # @contacts = Contact.all
    @contacts = Contact.order('created_at').page(params[:page]).per(1)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])
    @contact.status = 1
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@products = Product.order('created_at').page(params[:page]).per(1)
  end
end

app/controllers/introduces_controller.rb
class IntroducesController < ApplicationController
  # GET /introduces
  # GET /introduces.json
  def index
    @introduces = Introduce.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @introduces }
    end
  end

  # GET /introduces/1
  # GET /introduces/1.json
  def show
    @introduce = Introduce.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @introduce }
    end
  end

  # GET /introduces/new
  # GET /introduces/new.json
  def new
    @introduce = Introduce.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @introduce }
    end
  end

  # GET /introduces/1/edit
  def edit
    @introduce = Introduce.find(params[:id])
  end

  # POST /introduces
  # POST /introduces.json
  def create
    @introduce = Introduce.new(params[:introduce])

    respond_to do |format|
      if @introduce.save
        format.html { redirect_to @introduce, notice: 'Introduce was successfully created.' }
        format.json { render json: @introduce, status: :created, location: @introduce }
      else
        format.html { render action: "new" }
        format.json { render json: @introduce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /introduces/1
  # PUT /introduces/1.json
  def update
    @introduce = Introduce.find(params[:id])

    respond_to do |format|
      if @introduce.update_attributes(params[:introduce])
        format.html { redirect_to @introduce, notice: 'Introduce was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @introduce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /introduces/1
  # DELETE /introduces/1.json
  def destroy
    @introduce = Introduce.find(params[:id])
    @introduce.destroy

    respond_to do |format|
      format.html { redirect_to introduces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    # @products = Product.all
    @products = Product.order('created_at').page(params[:page]).per(1)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    # @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/introduces_helper.rb
module IntroducesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
     content_for(:title) { page_title }
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:js) { javascript_include_tag(*args) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/_company_address.html.haml
.contact_info
	%p 
		= t('company_name')
		=":" 
	%p 
		= t('company_address')
		=":"
	%p 
		= t('company_phone')
		=":"
	%p 
		= t('company_fax')
		=":"
	%p 
		= t('company_email')
		=":"

app/views/contacts/_form.html.haml
#createprofile.tab{:style => "display: block;", :class => params[:controller]}
  = simple_form_for @contact do |f|
    = f.error_notification
    = f.label t('contact_name')
    = f.input :name , :label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('contact_address')
    = f.input :address ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('contact_phone')
    = f.input :phone ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('contact_email')
    = f.input :email ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('contact_title')
    = f.input :title ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('contact_info')
    = f.input :description ,:label => false, :wrapper_html => {:class => "input_field"}
    .actions
      = f.button :submit  , :class => "btn" , :value => t('contact_save')

app/views/contacts/edit.html.haml
= title "Contact"
- content_for :left_side do
  = render 'shared/left_side'
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
= title "Contact"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('contact_list')
%table.contact_list.standard
  %tr
    %th.num
    %th.name.center
      =t('contact_name')
    %th.title.center
      =t('contact_title')
    %th.status.center
      =t('contact_status')
    %th.action
  - index = 0  
  - @contacts.each do |contact|
    %tr{:class => cycle("even" , "odd")}
      - index = index + 1
      %td.center
        = index
      %td= contact.name
      %td= contact.title
      %td.center
        - if contact.status == 1
          = t('contact_new')
        - else
          = t('contact_old')
      %td
        = link_to t('contact_show'), contact
        ="|"
        = link_to t('contact_delete'), contact, :confirm => 'Are you sure?', :method => :delete


= paginate @contacts

app/views/contacts/new.html.haml
= title "Contact"
- content_for :left_side do
  = render 'shared/left_side'
= render 'company_address'
= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
= title "Contact"
- content_for :left_side do
  = render 'shared/left_side'

%p#notice= notice

%p
  %b Name:
  = @contact.name
%p
  %b Address:
  = @contact.address
%p
  %b Phone:
  = @contact.phone
%p
  %b Email:
  = @contact.email
%p
  %b Title:
  = @contact.title
%p
  %b Description:
  = @contact.description

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/home/_slideshow.html.haml
#slideshow
	= image_tag('Demo/01.jpg')

app/views/home/index.html.haml
= render 'slideshow'
/ %p#news_title
/   ="Thong tin"
/ #news_content.news_content
/   %ul#index_sub_news
/     %li
/       &rsaquo;&rsaquo;
/       = link_to "  adsfaf asf asfasfaf " , "#"
/     %li.top_line
/       &rsaquo;&rsaquo;
/       = link_to " adsfaf asf asfasfaf " , "#"
/     %li.top_line
/       &rsaquo;&rsaquo;
/       = link_to " adsfaf asf asfasfaf " , "#"
/     %li.top_line
/       &rsaquo;&rsaquo;
/       = link_to " adsfaf asf asfasfaf " , "#"
/     %li.top_line
/       &rsaquo;&rsaquo;
/       = link_to " adsfaf asf asfasfaf " , "#"
/   #news_summary
/     %p.index_news_name
/       = "Statistically speaking"
/     %p.news_detail
/       = "Statistically speaking, it's likely that at some point in your life, someone has ladled a scoop of creamy rice pudding into a bowl for you. It may have been your grandmother or mother, perhaps the sweet old lady at the deli or cafeteria down the street, or maybe you just plucked a container of Kozy Shack ofnf the shelf at the grocery store and did the scooping yourself."
/     %p.news_link
/       = link_to "Chi tiet" , "#"

#news_content.news_content
  %p.home-title
    = t('home_title')
%p#news_title
  ="San pham dang ban"
.sub_products
  -index = 0
  - @products.each do |product|
    - if index == 0 
      .sub_produc_img
        = image_tag('Demo/img_demo.JPG')
        %p
          = link_to product.name , "#"
    - else
      .sub_produc_img.left_hline
        = image_tag('Demo/img_demo.JPG')
        %p
          = link_to "abc" , "#"

app/views/introduces/_form.html.haml
#createprofile.tab{:style => "display: block;", :class => params[:controller]}
  = simple_form_for @introduce do |f|
    = f.error_notification
    = f.label t('intro_title')
    = f.input :title , :label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('intro_summary')
    = f.input :summary ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('intro_content')
    = f.input :content ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('intro_img')
    = f.input :image ,:label => false, :wrapper_html => {:class => "input_field"}
    .actions
      = f.button :submit  , :class => "btn" , :value => t('save')

app/views/introduces/edit.html.haml
= title "Introduce"
- content_for :left_side do
  = render 'shared/left_side'
= title "Introduce"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('intro_input_info')
= render 'form'

= link_to 'Show', @introduce
\|
= link_to 'Back', introduces_path

app/views/introduces/index.html.haml
= title "Introduce"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('contact_list')

%table
  %tr
    %th Title
    %th Summary
    %th Content
    %th Image
    %th Author
    %th
    %th
    %th

  - @introduces.each do |introduce|
    %tr
      %td= introduce.title
      %td= introduce.summary
      %td= introduce.content
      %td= introduce.image
      %td= introduce.author
      %td= link_to 'Show', introduce
      %td= link_to 'Edit', edit_introduce_path(introduce)
      %td= link_to 'Destroy', introduce, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Introduce', new_introduce_path

app/views/introduces/new.html.haml
= title "Introduce"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('intro_input_info')
= render 'form'

= link_to 'Back', introduces_path

app/views/introduces/show.html.haml
= title "Introduce"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('intro_intro')
.introduce_content
  = image_tag('Demo/demo01.jpeg')
  .info_content
    %p
      = @introduce.title
    %p
      = @introduce.summary
    %p
      = @introduce.content

      

= link_to 'Edit', edit_introduce_path(@introduce)
\|
= link_to 'Back', introduces_path

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    = stylesheet_link_tag    "application", :media => "all"
    /[if lt IE 7]
      = stylesheet_link_tag 'ie/ie7', :media => 'all'
    = stylesheet_link_tag 'http://vjs.zencdn.net/c/video-js.css', :media => 'all'
    = javascript_include_tag "http://vjs.zencdn.net/c/video.js"
    = javascript_include_tag "head/application"
    = csrf_meta_tags
    = yield(:head)
    %title
      = (yield(:title) || "vanan")
  %body.without-right-side
    #page-wrapper
      #page{:class => "#{params[:controller]} #{params[:action]}"}
        #wrapper
          #header
            = render 'shared/header'
          #main
            .main-inner.clear-fix
              #left-side
                .left-side-inner.clear-fix= yield(:left_side)
              #contenter
                - flash.each do |name, msg|
                  = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
                = yield
          .clearboth
        #footer= render 'shared/footer'
  = javascript_include_tag "application"
  = yield(:js)

app/views/products/_form.html.haml
#createprofile.tab{:style => "display: block;", :class => params[:controller]}
  = simple_form_for @product do |f|
    = f.error_notification
    = f.label t('product_name')
    = f.input :name , :label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('product_price')
    = f.input :price ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('product_summary')
    = f.input :summary ,:label => false, :wrapper_html => {:class => "input_field"}
    = f.label t('product_desc')
    = f.input :description ,:label => false, :wrapper_html => {:class => "input_field"}
   
    .actions
      = f.button :submit  , :class => "btn" , :value => t('save')

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
= title "Product"
- content_for :left_side do
  = render 'shared/left_side'
%p.title
  = t('product_list')
%table.contact_list.standard
  %tr
    %th.num
    %th.name.center
      =t('product_name')
    %th.status.center
      =t('contact_status')
    %th.action
  - index = 0  
  - @products.each do |product|
    %tr{:class => cycle("even" , "odd")}
      - index = index + 1
      %td.center
        = index
      %td= product.name
      %td.center
        = product.status
      %td
        = link_to t('show'), product
        ="|"
        = link_to t('edit'), edit_product_path(product)
        ="|"
        = link_to t('delete'), product, :confirm => 'Are you sure?', :method => :delete


= paginate @products

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
= title "Contact"
- content_for :left_side do
  = render 'shared/left_side'

%p.title
  = t('product_add')
= render 'form'
= link_to t('product_list'), products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  / %b Name:
  / = @product.name
/ %p
/   %b Type:
/   = @product.type
/ %p
/   %b Summary:
/   = @product.summary
/ %p
/   %b Description:
/   = @product.description
/ %p
/   %b Status:
/   = @product.status
/ %p
/   %b Price:
/   = @product.price
/ %p
/   %b Image:
/   = @product.image

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path

app/views/shared/_footer.html.haml
#footer
  %p#footer_info
    = "© Copyright 2012 VANAN. Design by Hoang Nguyen "

app/views/shared/_header.html.haml
#banner
  %ul#topbanner
    %li#logo_content
      / = link_to image_tag('logo.jpg') , home_index_path
      = link_to image_tag('tpl.png') , home_index_path

      
    %li#top_link
      = "abc"

  %ul#top_menu_user
    %li#tab_dichvu
      = link_to t("introduc"), new_introduce_path
    %li#tab_thongtin
      = t('info') 
    %li#tab_sanpham
      = t('product')
    %li#tab_lienhe
      = link_to t('contact'), new_contact_path 
    

app/views/shared/_left_side.html.haml
#left_side
  %p.cust_support
    = "ABCD"
  %ul.support_info
    %li.phone_img
      =image_tag('contact_fone.gif')
    %li.phone_num
      %p 1234567890
      %p 1234567890

  %p.cust_support
    = "abcdf aaaa"
  .left_side_news
    %p.newshomepage-item 
      = " abafaf afafs afafsaf"
    %p.newshomepage-item 
      = " abafaf afafs afafsaf"
    %p.newshomepage-item 
      = " abafaf afafs afafsaf"
    %p.newshomepage-item 
      = " abafaf afafs afafsaf"